// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countTenants = `-- name: CountTenants :one
SELECT COUNT(*) FROM tenants
`

func (q *Queries) CountTenants(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTenants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlatformAdmin = `-- name: CreatePlatformAdmin :one
INSERT INTO platform_admins (email, password_hash, full_name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, full_name, created_at, updated_at
`

type CreatePlatformAdminParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	FullName     string `json:"full_name"`
}

func (q *Queries) CreatePlatformAdmin(ctx context.Context, arg CreatePlatformAdminParams) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, createPlatformAdmin, arg.Email, arg.PasswordHash, arg.FullName)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlatformAdminRefreshToken = `-- name: CreatePlatformAdminRefreshToken :one
INSERT INTO platform_admin_refresh_tokens (platform_admin_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, platform_admin_id, token_hash, expires_at, revoked_at, created_at
`

type CreatePlatformAdminRefreshTokenParams struct {
	PlatformAdminID uuid.UUID `json:"platform_admin_id"`
	TokenHash       string    `json:"token_hash"`
	ExpiresAt       time.Time `json:"expires_at"`
}

func (q *Queries) CreatePlatformAdminRefreshToken(ctx context.Context, arg CreatePlatformAdminRefreshTokenParams) (PlatformAdminRefreshToken, error) {
	row := q.db.QueryRow(ctx, createPlatformAdminRefreshToken, arg.PlatformAdminID, arg.TokenHash, arg.ExpiresAt)
	var i PlatformAdminRefreshToken
	err := row.Scan(
		&i.ID,
		&i.PlatformAdminID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformAdminByEmail = `-- name: GetPlatformAdminByEmail :one
SELECT id, email, password_hash, full_name, created_at, updated_at FROM platform_admins
WHERE email = $1
`

func (q *Queries) GetPlatformAdminByEmail(ctx context.Context, email string) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getPlatformAdminByEmail, email)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformAdminByID = `-- name: GetPlatformAdminByID :one
SELECT id, email, password_hash, full_name, created_at, updated_at FROM platform_admins
WHERE id = $1
`

func (q *Queries) GetPlatformAdminByID(ctx context.Context, id uuid.UUID) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getPlatformAdminByID, id)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformAdminRefreshTokenByHash = `-- name: GetPlatformAdminRefreshTokenByHash :one
SELECT id, platform_admin_id, token_hash, expires_at, revoked_at, created_at FROM platform_admin_refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetPlatformAdminRefreshTokenByHash(ctx context.Context, tokenHash string) (PlatformAdminRefreshToken, error) {
	row := q.db.QueryRow(ctx, getPlatformAdminRefreshTokenByHash, tokenHash)
	var i PlatformAdminRefreshToken
	err := row.Scan(
		&i.ID,
		&i.PlatformAdminID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, created_at, updated_at, status FROM tenants
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTenantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePlatformAdminRefreshToken = `-- name: RevokePlatformAdminRefreshToken :exec
UPDATE platform_admin_refresh_tokens
SET revoked_at = NOW()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokePlatformAdminRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokePlatformAdminRefreshToken, tokenHash)
	return err
}

const updateTenantStatus = `-- name: UpdateTenantStatus :one
UPDATE tenants
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, created_at, updated_at, status
`

type UpdateTenantStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantStatus, arg.ID, arg.Status)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}
