// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listBroadcasts = `-- name: ListBroadcasts :many
SELECT id, tenant_id, name, template_id, status, scheduled_at, sent_at, recipient_count, delivered_count, read_count, failed_count, error_message, created_by, created_at, updated_at FROM broadcasts
WHERE tenant_id = $1
  AND ($4::text IS NULL OR status = $4)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBroadcastsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
	Status   *string   `json:"status"`
}

func (q *Queries) ListBroadcasts(ctx context.Context, arg ListBroadcastsParams) ([]Broadcast, error) {
	rows, err := q.db.Query(ctx, listBroadcasts, arg.TenantID, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Broadcast
	for rows.Next() {
		var i Broadcast
		if err := rows.Scan(
			&i.ID, &i.TenantID, &i.Name, &i.TemplateID, &i.Status, &i.ScheduledAt, &i.SentAt,
			&i.RecipientCount, &i.DeliveredCount, &i.ReadCount, &i.FailedCount, &i.ErrorMessage,
			&i.CreatedBy, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const countBroadcasts = `-- name: CountBroadcasts :one
SELECT COUNT(*) FROM broadcasts
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2)
`

type CountBroadcastsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Status   *string   `json:"status"`
}

func (q *Queries) CountBroadcasts(ctx context.Context, arg CountBroadcastsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBroadcasts, arg.TenantID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBroadcastByID = `-- name: GetBroadcastByID :one
SELECT id, tenant_id, name, template_id, status, scheduled_at, sent_at, recipient_count, delivered_count, read_count, failed_count, error_message, created_by, created_at, updated_at FROM broadcasts
WHERE id = $1 AND tenant_id = $2
`

type GetBroadcastByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetBroadcastByID(ctx context.Context, arg GetBroadcastByIDParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, getBroadcastByID, arg.ID, arg.TenantID)
	var i Broadcast
	err := row.Scan(
		&i.ID, &i.TenantID, &i.Name, &i.TemplateID, &i.Status, &i.ScheduledAt, &i.SentAt,
		&i.RecipientCount, &i.DeliveredCount, &i.ReadCount, &i.FailedCount, &i.ErrorMessage,
		&i.CreatedBy, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const createBroadcast = `-- name: CreateBroadcast :one
INSERT INTO broadcasts (
    tenant_id, name, template_id, status, scheduled_at, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, tenant_id, name, template_id, status, scheduled_at, sent_at, recipient_count, delivered_count, read_count, failed_count, error_message, created_by, created_at, updated_at
`

type CreateBroadcastParams struct {
	TenantID    uuid.UUID  `json:"tenant_id"`
	Name        string     `json:"name"`
	TemplateID  uuid.UUID  `json:"template_id"`
	Status      string     `json:"status"`
	ScheduledAt *time.Time `json:"scheduled_at"`
	CreatedBy   uuid.UUID  `json:"created_by"`
}

func (q *Queries) CreateBroadcast(ctx context.Context, arg CreateBroadcastParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, createBroadcast, arg.TenantID, arg.Name, arg.TemplateID, arg.Status, arg.ScheduledAt, arg.CreatedBy)
	var i Broadcast
	err := row.Scan(
		&i.ID, &i.TenantID, &i.Name, &i.TemplateID, &i.Status, &i.ScheduledAt, &i.SentAt,
		&i.RecipientCount, &i.DeliveredCount, &i.ReadCount, &i.FailedCount, &i.ErrorMessage,
		&i.CreatedBy, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const updateBroadcastStatus = `-- name: UpdateBroadcastStatus :one
UPDATE broadcasts
SET status = $3,
    sent_at = CASE WHEN $3 = 'sent' THEN NOW() ELSE sent_at END,
    error_message = $4,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, template_id, status, scheduled_at, sent_at, recipient_count, delivered_count, read_count, failed_count, error_message, created_by, created_at, updated_at
`

type UpdateBroadcastStatusParams struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Status       string    `json:"status"`
	ErrorMessage *string   `json:"error_message"`
}

func (q *Queries) UpdateBroadcastStatus(ctx context.Context, arg UpdateBroadcastStatusParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, updateBroadcastStatus, arg.ID, arg.TenantID, arg.Status, arg.ErrorMessage)
	var i Broadcast
	err := row.Scan(
		&i.ID, &i.TenantID, &i.Name, &i.TemplateID, &i.Status, &i.ScheduledAt, &i.SentAt,
		&i.RecipientCount, &i.DeliveredCount, &i.ReadCount, &i.FailedCount, &i.ErrorMessage,
		&i.CreatedBy, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const templateExistsForTenant = `-- name: TemplateExistsForTenant :one
SELECT EXISTS(
    SELECT 1 FROM templates WHERE id = $1 AND tenant_id = $2
) AS exists
`

type TemplateExistsForTenantParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) TemplateExistsForTenant(ctx context.Context, arg TemplateExistsForTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, templateExistsForTenant, arg.ID, arg.TenantID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (tenant_id, name, status)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, status, created_at, updated_at
`

type CreateTemplateParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	Status   string    `json:"status"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate, arg.TenantID, arg.Name, arg.Status)
	var i Template
	err := row.Scan(&i.ID, &i.TenantID, &i.Name, &i.Status, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, tenant_id, name, status, created_at, updated_at FROM templates
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTemplatesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(&i.ID, &i.TenantID, &i.Name, &i.Status, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const countTemplates = `-- name: CountTemplates :one
SELECT COUNT(*) FROM templates
WHERE tenant_id = $1
`

func (q *Queries) CountTemplates(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTemplates, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, tenant_id, status, created_at, updated_at FROM conversations
WHERE tenant_id = $1
  AND ($4::text IS NULL OR status = $4)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListConversationsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
	Status   *string   `json:"status"`
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations, arg.TenantID, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(&i.ID, &i.TenantID, &i.Status, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const countConversations = `-- name: CountConversations :one
SELECT COUNT(*) FROM conversations
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2)
`

type CountConversationsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Status   *string   `json:"status"`
}

func (q *Queries) CountConversations(ctx context.Context, arg CountConversationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConversations, arg.TenantID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}
